apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/kubernetes-id: ci-cluster
  name: my-kubernetes-component
spec:
  lifecycle: production
  owner: my-team
  type: service
